import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <div className=" border-2 border-red-600">
          <p> This is Root Labout</p>
          {children}
        </div>
      </body>
    </html>
  );
}
