import Navbar from "@/components/Navbar";
import "./globals.css";
import { Cedarville_Cursive } from 'next/font/google';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const cursive = Cedarville_Cursive({
  weight: '400',
  subsets: ['latin'],
})


export default function RootLayout({ children }) {
  return (
    <html className={cursive.className}>
      <body className="min-h-screen border m-1 border-white">
        <div className=" border-2 border-red-600">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
